#!/usr/bin/env bash

#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License
#

##
## This script creates the Podman site for access to/from local bare-metal workloads.
##

FILE=declared-site.yaml
NAMESPACE=npdemo
APIVERSION=v2alpha1

cat >${FILE} <<EOF
---
apiVersion: skupper.io/${APIVERSION}
kind: Site
metadata:
  name: legacyhost
---
apiVersion: skupper.io/${APIVERSION}
kind: Connector
metadata:
  name: postgres
spec:
  routingKey: db
  port: 5432
  host: 10.110.222.236
EOF

for tok in token-*.yaml;
do
    cat >>${FILE} <<EOF
---
EOF
    cat ${tok} >>${FILE}
done

skupper --platform podman -n ${NAMESPACE} system apply -f ${FILE}
skupper --platform podman -n ${NAMESPACE} system start

